// Generated by https://quicktype.io

export interface HTTPErrorResponse {
    headers:    Headers;
    status:     number;
    statusText: string;
    url:        string;
    ok:         boolean;
    name:       string;
    message:    string;
    error:      HTTPErrorResponseError;
}

export interface HTTPErrorResponseError {
    error: NormalizedNamesClass;
    text:  string;
}

export interface NormalizedNamesClass {
}

export interface Headers {
    normalizedNames: NormalizedNamesClass;
    lazyUpdate:      null;
}
